services:
  ms-sales-sync-hub:
    build: .
    container_name: crm-endpoints
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - VIRTUAL_HOST=sales-hub-crm.duckdns.org # Reemplaza con el subdominio de tu backend
      - VIRTUAL_PORT=5000
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=sales-hub-crm.duckdns.org # Reemplaza con el subdominio de tu backend
      - LETSENCRYPT_EMAIL=plls
    networks:
      - mi_signes_networks

networks:
  mi_signes_networks:
    external: true
